export const MEDICINE_CATEGORIES = [
  'ANTIBIOTICS',
  'ANALGESICS',
  'ANTIHYPERTENSIVES',
  'ANTIDIABETICS',
  'ANTACIDS',
  'VITAMINS',
  'DERMATOLOGICAL',
  'RESPIRATORY',
  'CARDIOVASCULAR',
  'OTHER',
] as const
